# Generated by Django 5.0.4 on 2024-05-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(null=True)),
                ('image', models.ImageField(upload_to='')),
                ('recommended', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('bestsellers', models.BooleanField(default=False)),
                ('sale', models.BooleanField(default=False)),
                ('popular', models.BooleanField(default=False)),
                ('year', models.IntegerField(null=True)),
                ('developer', models.CharField(max_length=50, null=True)),
                ('budget', models.ManyToManyField(to='marketplace.budget')),
                ('category', models.ManyToManyField(to='marketplace.category')),
                ('platform', models.ManyToManyField(to='marketplace.platform')),
            ],
        ),
    ]
