# Generated by Django 5.0.4 on 2024-05-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='budget',
        ),
        migrations.AddField(
            model_name='game',
            name='budget',
            field=models.CharField(choices=[('INDIE', 'INDIE'), ('AA', 'AA'), ('AAA', 'AAA')], max_length=20, null=True),
        ),
    ]
