# Generated by Django 5.0.4 on 2024-05-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('recommended', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('bestsellers', models.BooleanField(default=False)),
                ('sale', models.BooleanField(default=False)),
                ('popular', models.BooleanField(default=False)),
                ('year', models.IntegerField()),
                ('category', models.CharField(choices=[('RPG', 'RPG'), ('Action', 'Action'), ('FPS', 'FPS'), ('PLatformer', 'PLatformer'), ('Open-World', 'Open-World')], max_length=20)),
                ('budget', models.CharField(choices=[('INDIE', 'INDIE'), ('AA', 'AA'), ('AAA', 'AAA')], max_length=20)),
                ('developer', models.CharField(max_length=50)),
                ('platform', models.CharField(choices=[('PC', 'PC'), ('Other', 'Other')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='TestItem',
        ),
    ]
