# Generated by Django 5.0.4 on 2024-05-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_game_budget_game_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='budget',
            field=models.CharField(choices=[('NONE', 'NONE'), ('INDIE', 'INDIE'), ('AA', 'AA'), ('AAA', 'AAA'), ('AAAA', 'AAAA')], max_length=20, null=True),
        ),
    ]
