# Generated by Django 5.0.4 on 2024-05-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_game_delete_testitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='budget',
            field=models.CharField(choices=[('INDIE', 'INDIE'), ('AA', 'AA'), ('AAA', 'AAA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('RPG', 'RPG'), ('Action', 'Action'), ('FPS', 'FPS'), ('PLatformer', 'PLatformer'), ('Open-World', 'Open-World')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('PC', 'PC'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
