# Generated by Django 5.0.4 on 2024-05-29 13:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_game_budget_alter_game_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('RPG', 'RPG'), ('Action', 'Action'), ('FPS', 'FPS'), ('PLatformer', 'PLatformer'), ('Open-World', 'Open-World')], max_length=100, null=True), blank=True, null=True, size=None),
        ),
    ]
