# Generated by Django 5.0.4 on 2024-05-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_game_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
