# Generated by Django 5.0.4 on 2024-06-04 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_game_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
